#!/usr/bin/env bash

npx prettier@2.3.2 -w \
  'bench/*.{js,json}' \
  'bench/runners/*.{js,json}' \
  'bench/runners/*/*.{js,json}' \
  'minify-html-nodejs/*.{js,json,ts}' \
  'version'

cargo +nightly fmt
